// Mocks generated by Mockito 5.4.4 from annotations
// in auto_sync_plus/test/auto_sync_plus_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i10;

import 'package:auto_sync_plus/auto_sync_plus.dart' as _i6;
import 'package:file/file.dart' as _i5;
import 'package:flutter_cache_manager/flutter_cache_manager.dart' as _i2;
import 'package:flutter_cache_manager/src/cache_store.dart' as _i3;
import 'package:flutter_cache_manager/src/web/web_helper.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

import 'util/api_repo.dart' as _i11;
import 'util/post_dto.dart' as _i7;
import 'util/posts_dto.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConfig_0 extends _i1.SmartFake implements _i2.Config {
  _FakeConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheStore_1 extends _i1.SmartFake implements _i3.CacheStore {
  _FakeCacheStore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebHelper_2 extends _i1.SmartFake implements _i4.WebHelper {
  _FakeWebHelper_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_3 extends _i1.SmartFake implements _i5.File {
  _FakeFile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileInfo_4 extends _i1.SmartFake implements _i2.FileInfo {
  _FakeFileInfo_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoSyncPlus_5 extends _i1.SmartFake implements _i6.AutoSyncPlus {
  _FakeAutoSyncPlus_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostDto_6 extends _i1.SmartFake implements _i7.PostDto {
  _FakePostDto_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostsDto_7 extends _i1.SmartFake implements _i8.PostsDto {
  _FakePostsDto_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DefaultCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDefaultCacheManager extends _i1.Mock
    implements _i2.DefaultCacheManager {
  MockDefaultCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Config get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeConfig_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.Config);

  @override
  _i3.CacheStore get store => (super.noSuchMethod(
        Invocation.getter(#store),
        returnValue: _FakeCacheStore_1(
          this,
          Invocation.getter(#store),
        ),
      ) as _i3.CacheStore);

  @override
  _i4.WebHelper get webHelper => (super.noSuchMethod(
        Invocation.getter(#webHelper),
        returnValue: _FakeWebHelper_2(
          this,
          Invocation.getter(#webHelper),
        ),
      ) as _i4.WebHelper);

  @override
  _i9.Future<_i5.File> getSingleFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSingleFile,
          [url],
          {
            #key: key,
            #headers: headers,
          },
        ),
        returnValue: _i9.Future<_i5.File>.value(_FakeFile_3(
          this,
          Invocation.method(
            #getSingleFile,
            [url],
            {
              #key: key,
              #headers: headers,
            },
          ),
        )),
      ) as _i9.Future<_i5.File>);

  @override
  _i9.Stream<_i2.FileInfo> getFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFile,
          [url],
          {
            #key: key,
            #headers: headers,
          },
        ),
        returnValue: _i9.Stream<_i2.FileInfo>.empty(),
      ) as _i9.Stream<_i2.FileInfo>);

  @override
  _i9.Stream<_i2.FileResponse> getFileStream(
    String? url, {
    String? key,
    Map<String, String>? headers,
    bool? withProgress = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileStream,
          [url],
          {
            #key: key,
            #headers: headers,
            #withProgress: withProgress,
          },
        ),
        returnValue: _i9.Stream<_i2.FileResponse>.empty(),
      ) as _i9.Stream<_i2.FileResponse>);

  @override
  _i9.Future<_i2.FileInfo> downloadFile(
    String? url, {
    String? key,
    Map<String, String>? authHeaders,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [url],
          {
            #key: key,
            #authHeaders: authHeaders,
            #force: force,
          },
        ),
        returnValue: _i9.Future<_i2.FileInfo>.value(_FakeFileInfo_4(
          this,
          Invocation.method(
            #downloadFile,
            [url],
            {
              #key: key,
              #authHeaders: authHeaders,
              #force: force,
            },
          ),
        )),
      ) as _i9.Future<_i2.FileInfo>);

  @override
  _i9.Future<_i2.FileInfo?> getFileFromCache(
    String? key, {
    bool? ignoreMemCache = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileFromCache,
          [key],
          {#ignoreMemCache: ignoreMemCache},
        ),
        returnValue: _i9.Future<_i2.FileInfo?>.value(),
      ) as _i9.Future<_i2.FileInfo?>);

  @override
  _i9.Future<_i2.FileInfo?> getFileFromMemory(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileFromMemory,
          [key],
        ),
        returnValue: _i9.Future<_i2.FileInfo?>.value(),
      ) as _i9.Future<_i2.FileInfo?>);

  @override
  _i9.Future<_i5.File> putFile(
    String? url,
    _i10.Uint8List? fileBytes, {
    String? key,
    String? eTag,
    Duration? maxAge = const Duration(days: 30),
    String? fileExtension = r'file',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putFile,
          [
            url,
            fileBytes,
          ],
          {
            #key: key,
            #eTag: eTag,
            #maxAge: maxAge,
            #fileExtension: fileExtension,
          },
        ),
        returnValue: _i9.Future<_i5.File>.value(_FakeFile_3(
          this,
          Invocation.method(
            #putFile,
            [
              url,
              fileBytes,
            ],
            {
              #key: key,
              #eTag: eTag,
              #maxAge: maxAge,
              #fileExtension: fileExtension,
            },
          ),
        )),
      ) as _i9.Future<_i5.File>);

  @override
  _i9.Future<_i5.File> putFileStream(
    String? url,
    _i9.Stream<List<int>>? source, {
    String? key,
    String? eTag,
    Duration? maxAge = const Duration(days: 30),
    String? fileExtension = r'file',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putFileStream,
          [
            url,
            source,
          ],
          {
            #key: key,
            #eTag: eTag,
            #maxAge: maxAge,
            #fileExtension: fileExtension,
          },
        ),
        returnValue: _i9.Future<_i5.File>.value(_FakeFile_3(
          this,
          Invocation.method(
            #putFileStream,
            [
              url,
              source,
            ],
            {
              #key: key,
              #eTag: eTag,
              #maxAge: maxAge,
              #fileExtension: fileExtension,
            },
          ),
        )),
      ) as _i9.Future<_i5.File>);

  @override
  _i9.Future<void> removeFile(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeFile,
          [key],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyCache() => (super.noSuchMethod(
        Invocation.method(
          #emptyCache,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<_i2.FileResponse> getImageFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
    bool? withProgress = false,
    int? maxHeight,
    int? maxWidth,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImageFile,
          [url],
          {
            #key: key,
            #headers: headers,
            #withProgress: withProgress,
            #maxHeight: maxHeight,
            #maxWidth: maxWidth,
          },
        ),
        returnValue: _i9.Stream<_i2.FileResponse>.empty(),
      ) as _i9.Stream<_i2.FileResponse>);
}

/// A class which mocks [ApiRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiRepo extends _i1.Mock implements _i11.ApiRepo {
  MockApiRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AutoSyncPlus get autoSync => (super.noSuchMethod(
        Invocation.getter(#autoSync),
        returnValue: _FakeAutoSyncPlus_5(
          this,
          Invocation.getter(#autoSync),
        ),
      ) as _i6.AutoSyncPlus);

  @override
  _i9.Stream<double> syncAllDataWithProgress() => (super.noSuchMethod(
        Invocation.method(
          #syncAllDataWithProgress,
          [],
        ),
        returnValue: _i9.Stream<double>.empty(),
      ) as _i9.Stream<double>);

  @override
  _i9.Future<_i7.PostDto> getPost() => (super.noSuchMethod(
        Invocation.method(
          #getPost,
          [],
        ),
        returnValue: _i9.Future<_i7.PostDto>.value(_FakePostDto_6(
          this,
          Invocation.method(
            #getPost,
            [],
          ),
        )),
      ) as _i9.Future<_i7.PostDto>);

  @override
  _i9.Future<_i8.PostsDto> getPosts() => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
        ),
        returnValue: _i9.Future<_i8.PostsDto>.value(_FakePostsDto_7(
          this,
          Invocation.method(
            #getPosts,
            [],
          ),
        )),
      ) as _i9.Future<_i8.PostsDto>);
}
