name: auto_sync_plus
description: "Auto Sync Plus for JSON responses & files."
version: 0.0.2
homepage: https://github.com/prakashbahadurchand/auto_sync_plus

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.0
  crypto: ^3.0.6
  dio: ^5.7.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  syncfusion_flutter_pdfviewer: ^27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
